export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const ADD_NEW_ORDER_DONE = 'ADD_NEW_ORDER_DONE';
export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const CHECK_ORDER_DONE = 'CHECK_ORDER_DONE';
export const CANCEL_ORDER = 'CANCEL_ORDER';