export const GET_LIST_SHIPPING_INFO = 'GET_LIST_SHIPPING_INFO';
export const ADD_NEW_SHIPPING_INFO = 'ADD_NEW_SHIPPING_INFO';
export const UPDATE_SHIPPING_INFO = 'UPDATE_SHIPPING_INFO';
export const GET_LIST_CITY = 'GET_LIST_CITY';
export const GET_LIST_DISTRICT = 'GET_LIST_DISTRICT';
export const GET_LIST_WARD = 'GET_LIST_WARD';
export const DELETE_SHIPPING_INFO = 'DELETE_SHIPPING_INFO';